# Generated by Django 5.2.13 on 2026-04-19 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_index', models.IntegerField()),
                ('image_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='events.event')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'sequence_index'], name='frames_fram_event_i_28e42b_idx')],
                'unique_together': {('event', 'sequence_index')},
            },
        ),
    ]
