# Generated by Django 5.2.9 on 2026-02-04 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('mac_address', models.CharField(db_index=True, help_text='MAC address of ESP32-CAM (format: XX:XX:XX:XX:XX:XX)', max_length=17, unique=True)),
                ('name', models.CharField(help_text="Custom name for the camera (e.g., 'Living Room Cam')", max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Physical location of camera', max_length=255, null=True)),
                ('motion_detection_enabled', models.BooleanField(default=True)),
                ('motion_sensitivity', models.IntegerField(default=80, help_text='Motion detection sensitivity (0-100)')),
                ('snapshot_interval', models.IntegerField(default=300, help_text='Snapshot interval in seconds (0 = disabled)')),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('battery_level', models.IntegerField(blank=True, help_text='Battery percentage (if applicable)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CameraAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('viewer', 'Viewer')], max_length=10)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_list', to='camstats.camera')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_invitation_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Camera Access',
                'verbose_name_plural': 'Camera Access',
                'ordering': ['camera', 'role'],
                'unique_together': {('user', 'camera')},
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='users',
            field=models.ManyToManyField(related_name='cameras', through='camstats.CameraAccess', through_fields=('camera', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MotionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot_url', models.URLField(blank=True, help_text='URL to snapshot image', null=True)),
                ('video_url', models.URLField(blank=True, help_text='URL to recorded video clip', null=True)),
                ('confidence', models.IntegerField(default=0, help_text='Motion detection confidence (0-100)')),
                ('duration', models.IntegerField(blank=True, help_text='Duration of motion in seconds', null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_events', to='camstats.camera')),
                ('notified_users', models.ManyToManyField(blank=True, related_name='motion_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motion Event',
                'verbose_name_plural': 'Motion Events',
                'ordering': ['-detected_at'],
            },
        ),
    ]
