# Generated by Django 5.2.13 on 2026-04-19 18:37

import devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='api_key',
            field=models.CharField(db_index=True, default=devices.models.generate_api_key, max_length=64, unique=True),
        ),
    ]
